from time import time
from wallet import Wallet
from utility.printable import Printable
from requests import get
from utility.hash_util import *


class Block(Printable):
    """A single block of our blockchain.

    Attributes:
        :index: The index of this block.
        :previous_hash: The hash of the previous block in the blockchain.
        :timestamp: The timestamp of the block (automatically generated by
        default).
        :transactions: A list of transaction which are included in the block.
        :proof: The proof of work number that yielded this block.
    """

    def __init__(self, index, previous_hash, transactions, proof, time=time()):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = time
        self.transactions = transactions
        self.proof = proof
        # ip = get('https://api.ipify.org').text
        # ip = str(ip).encode('utf-8')
        # id = hash_string_256(ip)
        # wallet = Wallet(id)
        # self.node = wallet.node_id
